// Utilities
import { fileURLToPath, URL } from 'node:url';
import Vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';

// Plugins
import Vuetify, { transformAssetUrls } from 'vite-plugin-vuetify';

// https://vitejs.dev/config/
export default defineConfig({
  base: './',
  plugins: [
    Vue({
      template: { transformAssetUrls },
    }),
    // https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin#readme
    Vuetify({
      autoImport: true,
    }),
  ],
  optimizeDeps: {
    exclude: [
      'vuetify',
    ],
    // Generated by Copilot - Include local @wwtelescope packages for pre-bundling (they use CommonJS)
    include: [
      '@wwtelescope/engine-pinia',
    ],
  },
  define: { 'process.env': {} },
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('src', import.meta.url)),
      // Generated by Copilot - Point to ESM/dist builds for local @wwtelescope packages
      '@wwtelescope/engine': '/Users/jal194/github/wwt-webgl-engine/engine/esm/index.js',
      '@wwtelescope/engine-pinia': '/Users/jal194/github/wwt-webgl-engine/engine-pinia/src/index.ts',
      '@wwtelescope/engine-helpers': '/Users/jal194/github/wwt-webgl-engine/engine-helpers/dist/src/index.js',
      '@wwtelescope/engine-types': '/Users/jal194/github/wwt-webgl-engine/engine-types/dist/src/index.js',
      '@wwtelescope/astro': '/Users/jal194/github/wwt-webgl-engine/astro/dist/src/index.js',
    },
    extensions: [
      '.js',
      '.json',
      '.jsx',
      '.mjs',
      '.ts',
      '.tsx',
      '.vue',
    ],
  },
  server: {},
  css: {
    preprocessorOptions: {
      less: {
        math: 'always',
      },
    },
  },
});
