<!-- Generated by Copilot -->
<template>
  <v-card class="orbital-editor">
    <v-card-title class="text-subtitle-1 py-2">Orbital Elements Editor</v-card-title>
    <v-card-text class="pa-2">
      <!-- Position display -->
      <div v-if="currentPosition" class="position-display">
        <div class="position-title">Position at Epoch (JD {{ localElements.jdEquinox?.toFixed(2) }}):</div>
        <div class="position-coords">
          x: {{ (currentPosition.x).toFixed(6) }} AU<br>
          y: {{ (currentPosition.y).toFixed(6) }} AU<br>
          z: {{ (currentPosition.z).toFixed(6) }} AU
        </div>
      </div>

      <div class="element-row">
        <label class="element-label">a (AU)</label>
        <input
          v-model.number="localElements.a"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.a"
          type="range"
          :min="0.1"
          :max="50"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('a') }}</span>
        <button class="reset-btn" @click="resetElement('a')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">e</label>
        <input
          v-model.number="localElements.e"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.e"
          type="range"
          :min="0"
          :max="0.99"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('e') }}</span>
        <button class="reset-btn" @click="resetElement('e')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">i (°)</label>
        <input
          v-model.number="localElements.i"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.i"
          type="range"
          :min="-90"
          :max="90"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('i') }}</span>
        <button class="reset-btn" @click="resetElement('i')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">Ω (°)</label>
        <input
          v-model.number="localElements.omega"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.omega"
          type="range"
          :min="0"
          :max="360"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('omega') }}</span>
        <button class="reset-btn" @click="resetElement('omega')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">ω (°)</label>
        <input
          v-model.number="localElements.w"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.w"
          type="range"
          :min="0"
          :max="360"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('w') }}</span>
        <button class="reset-btn" @click="resetElement('w')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">M (°)</label>
        <input
          v-model.number="localElements.meanAnnomolyOut"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.meanAnnomolyOut"
          type="range"
          :min="-360"
          :max="360"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('meanAnnomolyOut') }}</span>
        <button class="reset-btn" @click="resetElement('meanAnnomolyOut')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">n (°/d)</label>
        <input
          v-model.number="localElements.n"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.n"
          type="range"
          :min="0"
          :max="1"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('n') }}</span>
        <button class="reset-btn" @click="resetElement('n')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>

      <div class="element-row">
        <label class="element-label">JD</label>
        <input
          v-model.number="localElements.jdEquinox"
          type="number"
          :step="0.0001"
          class="element-input"
          @input="updateOrbit"
        />
        <input
          v-model.number="localElements.jdEquinox"
          type="range"
          :min="2400000"
          :max="2500000"
          :step="0.0001"
          class="element-slider"
          @input="updateOrbit"
        />
        <span class="delta-display">{{ getDelta('jdEquinox') }}</span>
        <button class="reset-btn" @click="resetElement('jdEquinox')">
          <v-icon size="x-small">mdi-refresh</v-icon>
        </button>
      </div>
    </v-card-text>
  </v-card>
</template>

<script setup lang="ts">
import { ref, watch, computed, type PropType } from 'vue';
import { ReferenceFrame, LayerManager, ELL } from '@wwtelescope/engine';
import type { OrbitLayer, EOE } from '@wwtelescope/engine';
import { AltUnits } from '@wwtelescope/engine-types';
import { AU_KM } from '../constants';

const AU_TO_METERS = 149597870700;

const props = defineProps({
  orbitLayer: {
    type: Object as PropType<OrbitLayer | null>,
    required: true
  }
});

// Default/initial orbital elements (store original values)
const defaultElements = ref<EOE>({
  a: 3.1,
  e: 0.25,
  i: 2.7,
  w: 197,
  omega: 121,
  meanAnnomolyOut: 120,
  n: 0.18,
  t: 2460334.79,
  jdEquinox: 2461000.5
});

// Local copy of orbital elements for editing
const localElements = ref<EOE>({ ...defaultElements.value });

// Computed position at the current epoch
const currentPosition = computed(() => {
  if (!localElements.value.jdEquinox) return null;
  
  try {
    const position = ELL.calculateRectangularJD(localElements.value.jdEquinox, localElements.value);
    return position;
  } catch (e) {
    console.error('Error calculating position:', e);
    return null;
  }
});

// Initialize local elements from the layer
watch(
  () => props.orbitLayer,
  (layer) => {
    if (layer) {
      const frames = layer.get_frames();
      if (frames && frames.length > 0) {
        const frame = frames[0];
        if (!frame) return;
        
        // Get orbital elements - convert semi-major axis from meters to AU
        const elements = {
          a: frame.semiMajorAxis / AU_TO_METERS,  // Convert meters to AU
          e: frame.eccentricity,
          i: frame.inclination,
          w: frame.argumentOfPeriapsis,
          omega: frame.longitudeOfAscendingNode,
          meanAnnomolyOut: frame.meanAnomolyAtEpoch,
          n: frame.meanDailyMotion,
          t: frame.epoch,
          jdEquinox: frame.epoch
        };
        
        // Store as default and current values
        defaultElements.value = { ...elements };
        localElements.value = { ...elements };
      }
    }
  },
  { immediate: true }
);

/**
 * Updates the orbit layer with the modified orbital elements
 * Modifies the frame in place rather than replacing it
 */
function updateOrbit() {
  if (!props.orbitLayer) return;

  const frames = props.orbitLayer.get_frames();
  if (!frames || frames.length === 0) return;

  // Get the current frame
  const frame = frames[0];
  if (!frame) return;

  // Update orbital elements directly on the frame (convert AU to meters for semi-major axis)
  frame.semiMajorAxis = localElements.value.a * AU_TO_METERS;
  frame.semiMajorAxisUnits = AltUnits.meters;
  frame.eccentricity = localElements.value.e;
  frame.inclination = localElements.value.i;
  frame.argumentOfPeriapsis = localElements.value.w;
  frame.longitudeOfAscendingNode = localElements.value.omega;
  frame.meanAnomolyAtEpoch = localElements.value.meanAnnomolyOut ?? 0;
  frame.meanDailyMotion = localElements.value.n;
  frame.epoch = localElements.value.jdEquinox;

  // Clear the old orbit so it gets recalculated
  frame._orbit = null;

  // Increment version to trigger a redraw
  LayerManager.set_version(LayerManager.get_version() + 1);
  LayerManager.loadTree();

  console.log('Updated orbital elements (AU):', localElements.value);
  console.log('Frame semi-major axis (meters):', frame.semiMajorAxis);
}

/**
 * Resets a single orbital element to its default value
 */
function resetElement(key: keyof EOE) {
  const defaultValue = defaultElements.value[key];
  if (defaultValue !== undefined) {
    localElements.value[key] = defaultValue as any;
    updateOrbit();
  }
}

/**
 * Gets the delta (difference) between current and default value
 */
function getDelta(key: keyof EOE): string {
  const current = localElements.value[key];
  const original = defaultElements.value[key];
  
  if (current === undefined || original === undefined) return '';
  
  const delta = current - original;
  
  if (Math.abs(delta) < 0.0001) return '';
  
  const sign = delta > 0 ? '+' : '';
  return `${sign}${delta.toFixed(5)}`;
}
</script>

<style scoped>
.orbital-editor {
  max-height: 80vh;
  overflow-y: auto;
  font-size: 12px;
}

.element-row {
  display: grid;
  grid-template-columns: 50px 70px 1fr 50px 30px;
  gap: 6px;
  align-items: center;
  margin-bottom: 6px;
}

.element-label {
  font-size: 11px;
  font-weight: 500;
  text-align: right;
  color: #fff;
}

.element-input {
  width: 100%;
  padding: 2px 4px;
  font-size: 11px;
  border: 1px solid #555;
  border-radius: 3px;
  background: #2a2a2a;
  color: #fff;
}

.element-input:focus {
  outline: none;
  border-color: #1976d2;
}

.element-slider {
  width: 100%;
  height: 4px;
  -webkit-appearance: none;
  appearance: none;
  background: #555;
  outline: none;
  border-radius: 2px;
}

.element-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #1976d2;
  cursor: pointer;
}

.element-slider::-moz-range-thumb {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #1976d2;
  cursor: pointer;
  border: none;
}

.reset-btn {
  width: 24px;
  height: 24px;
  padding: 0;
  font-size: 14px;
  border: 1px solid #555;
  border-radius: 3px;
  background: #2a2a2a;
  color: #fff;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.reset-btn:hover {
  background: #3a3a3a;
  border-color: #1976d2;
}

.reset-btn:active {
  background: #1976d2;
}

.delta-display {
  font-size: 10px;
  text-align: right;
  color: #aaa;
  font-family: monospace;
}

.position-display {
  margin-bottom: 12px;
  padding: 8px;
  background: #1a1a1a;
  border-radius: 4px;
  border: 1px solid #444;
}

.position-title {
  font-size: 11px;
  font-weight: 600;
  color: #1976d2;
  margin-bottom: 4px;
}

.position-coords {
  font-size: 10px;
  color: #fff;
  font-family: monospace;
  line-height: 1.4;
}
</style>
