<template>
  <div class="orbit-comparison">
    <v-card class="orbit-comparison-card" color="#0f141c" elevation="8">
      <v-card-title class="card-title" @click="expanded = !expanded" style="cursor: pointer; user-select: none;">
        <span>Orbit Elements Comparison</span>
        <v-icon :icon="expanded ? 'mdi-chevron-up' : 'mdi-chevron-down'" size="small" class="ml-2" />
      </v-card-title>
      <v-expand-transition>
        <v-card-text v-show="expanded">
          <div class="controls">
            <v-select
              v-model="selectedJd"
              :items="jdOptions"
              label="JDTDB"
              hide-details
              density="compact"
              class="control"
            />
            <v-select
              v-model="viewMode"
              :items="viewOptions"
              label="Table"
              hide-details
              density="compact"
              class="control"
            />
          </div>

          <div class="tables">
            <div class="table-block" v-if="displayRow">
              <div class="table-header">{{ viewModeLabel }}</div>
              <pre class="block-text">{{ formatHorizonsBlock(displayRow).join("\n") }}</pre>
              <div v-if="displayPosition" class="position-display">
                <div class="position-label">Position at Epoch (ELL.calculateRectangularJD):</div>
                <div class="position-coords">
                  x: {{ displayPosition.x.toFixed(9) }} m ({{ (displayPosition.x/AU_M) }} AU)<br>
                  y: {{ displayPosition.y.toFixed(9) }} m ({{ (displayPosition.y/AU_M) }} AU)<br>
                  z: {{ displayPosition.z.toFixed(9) }} m ({{ (displayPosition.z/AU_M) }} AU)
                </div>
              </div>
            </div>

            <div class="table-block" v-if="diffRow">
              <div class="table-header">Difference (% of JPL)</div>
              <pre class="block-text">{{ formatHorizonsBlock(diffRow).join("\n") }}</pre>
            </div>
          </div>
        </v-card-text>
      </v-expand-transition>
    </v-card>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot
import { computed, ref, watch } from "vue";
import { ELL, SpaceTimeController } from "@wwtelescope/engine";
import type { OrbitLayer, ReferenceFrame, EOE } from "@wwtelescope/engine";
import { engineStore } from "@wwtelescope/engine-pinia";
import horizonsRaw from "../assets/osculating_orbital_elements.txt?raw";
import {
  formatHorizonsBlock,
  horizonsRowFromElements,
  parseHorizonsText,
  type HorizonsLikeRow,
  diffHorizonsRows,
} from "../orbit";
import { show3dPoint } from "@/spreadsheetLayer";
import { AU_M } from "../constants";

const props = defineProps<{
  orbitLayer: OrbitLayer | null;
}>();

const store = engineStore();

const parsedJplRows = parseHorizonsText(horizonsRaw);
const jdOptions = parsedJplRows.map((row) => ({ title: `${row.JDTDB.toFixed(6)}`, value: row.JDTDB }));
const selectedJd = ref(jdOptions[0]?.value ?? null);
const expanded = ref(false);

// 3D point visualization
let pointVisualizer: ReturnType<typeof show3dPoint> | null = null;

// Sync WWT time when JD selection changes and pause the clock
watch(selectedJd, (newJd) => {
  if (newJd !== null && store.$wwt.inst) {
    const date = SpaceTimeController.julianToUtc(newJd);
    store.$wwt.inst.stc.set_now(date);
    store.$wwt.inst.stc.set_syncToClock(false);
  }
}, { immediate: true });

const viewOptions = [
  { title: "Propagated", value: "propagated" },
  { title: "JPL", value: "jpl" },
];
const viewMode = ref("propagated");

const firstFrame = computed(() => {
  const layer = props.orbitLayer;
  if (!layer) return null as ReferenceFrame | null;

  const frames = typeof layer.get_frames === "function"
    ? layer.get_frames()
    : (layer as unknown as { frames?: ReferenceFrame[] }).frames;

  const frame = Array.isArray(frames) && frames.length > 0 ? frames[0] : null;
  return frame as ReferenceFrame | null;
});

const elements = computed<EOE | null>(() => {
  const frame = firstFrame.value as unknown as { get_elements?: () => EOE; _elements?: EOE } | null;
  if (!frame) return null;
  if (typeof frame.get_elements === "function") {
    return frame.get_elements();
  }
  if (frame._elements) {
    return frame._elements;
  }
  return null;
});

const selectedJplRow = computed<HorizonsLikeRow | null>(() => {
  if (selectedJd.value === null) return null;
  return parsedJplRows.find((row) => Math.abs(row.JDTDB - selectedJd.value!) < 1e-6) ?? null;
});

const propagatedRow = computed<HorizonsLikeRow | null>(() => {
  if (!elements.value || selectedJd.value === null) return null;
  return horizonsRowFromElements(elements.value, selectedJd.value);
});

const diffRow = computed<HorizonsLikeRow | null>(() => {
  if (!propagatedRow.value || !selectedJplRow.value) return null;
  return diffHorizonsRows(propagatedRow.value, selectedJplRow.value);
});

const displayRow = computed(() => {
  if (viewMode.value === "jpl") return selectedJplRow.value;
  return propagatedRow.value;
});

const displayPosition = computed(() => {
  if (!elements.value || selectedJd.value === null) return null;
  try {
    return ELL.calculateRectangularJD(selectedJd.value, elements.value);
  } catch (e) {
    console.error("Error calculating position:", e);
    return null;
  }
});

// Update 3D point visualization when position changes
watch(displayPosition, (pos) => {
  if (pos) {
    if (!pointVisualizer) {
      pointVisualizer = show3dPoint(0, 0, 0, { 
        name: "Jupiter@Epoch", 
        frame: "Sun",
        pointSize: 30,
        colorHex: "#FFAA00",
        inputConvention: "wwt",
      });
    }
    pointVisualizer.updateMeters(pos.x, pos.y, pos.z);
  }
}, { immediate: true });

const viewModeLabel = computed(() => viewMode.value === "jpl" ? "JPL Horizons" : "Propagated (WWT)");
</script>

<style scoped>
.orbit-comparison {
  width: 100%;
  max-width: 900px;
}

.orbit-comparison-card {
  width: 100%;
  color: #e5e9ef;
}

.card-title {
  font-weight: 700;
  letter-spacing: 0.02em;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.controls {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-bottom: 12px;
}

.control {
  min-width: 200px;
  flex: 1 1 200px;
}

.tables {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.table-block {
  width: 100%;
}

.table-header {
  font-size: 0.9rem;
  color: #9fc3ff;
  margin-bottom: 4px;
}

.block-text {
  background: linear-gradient(145deg, rgba(24, 29, 38, 0.9), rgba(15, 19, 25, 0.95));
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 6px;
  padding: 10px 12px;
  margin: 0;
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 0.82rem;
  color: #f0f3f8;
  white-space: pre;
  overflow-x: auto;
  width: 100%;
  box-sizing: border-box;
}

.position-display {
  margin-top: 8px;
  padding: 8px 12px;
  background: rgba(15, 19, 25, 0.6);
  border: 1px solid rgba(159, 195, 255, 0.2);
  border-radius: 4px;
}

.position-label {
  font-size: 0.75rem;
  color: #9fc3ff;
  margin-bottom: 4px;
  font-weight: 600;
}

.position-coords {
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 0.75rem;
  color: #f0f3f8;
  line-height: 1.5;
}
</style>
