<template>
  <div class="orbit-elements-table">
    <v-card
      class="orbit-elements-card"
      color="#11161d"
      variant="elevated"
      elevation="6"
    >
      <v-card-title class="card-title">
        {{ titleLabel }}
      </v-card-title>
      <v-card-text>
        <div
          v-if="!elementsAvailable"
          class="placeholder"
        >
          No orbit elements available yet.
        </div>
        <div v-else>
          <div
            v-for="row in rows"
            :key="row.JDTDB"
            class="row-block"
          >
            <div class="jd-line">JDTDB {{ formatJulianDate(row.JDTDB) }}</div>
            <pre class="block-text">{{ formatHorizonsBlock(row).join("\n") }}</pre>
          </div>
        </div>
      </v-card-text>
    </v-card>
  </div>
</template>

<script setup lang="ts">
// Generated by Copilot
import { computed } from "vue";
import type { OrbitLayer, ReferenceFrame, EOE } from "@wwtelescope/engine";
import {
  formatHorizonsBlock,
  formatJulianDate,
  horizonsRowFromElements,
  type HorizonsLikeRow,
} from "../orbit";

const props = defineProps<{
  orbitLayer: OrbitLayer | null;
  julianDates: number[];
  title?: string;
}>();

const firstFrame = computed(() => {
  const layer = props.orbitLayer;
  if (!layer) return null as ReferenceFrame | null;

  const frames = typeof layer.get_frames === "function"
    ? layer.get_frames()
    : (layer as unknown as { frames?: ReferenceFrame[] }).frames;

  const frame = Array.isArray(frames) && frames.length > 0 ? frames[0] : null;
  return frame as ReferenceFrame | null;
});

const elements = computed<EOE | null>(() => {
  const frame = firstFrame.value as unknown as { get_elements?: () => EOE; _elements?: EOE } | null;
  if (!frame) return null;
  if (typeof frame.get_elements === "function") {
    return frame.get_elements();
  }
  if (frame._elements) {
    return frame._elements;
  }
  return null;
});

const rows = computed<HorizonsLikeRow[]>(() => {
  if (!elements.value) return [];
  return props.julianDates.map((jd) => horizonsRowFromElements(elements.value as EOE, jd));
});

const titleLabel = computed(() => props.title ?? "Horizons-style elements");
const elementsAvailable = computed(() => !!elements.value && rows.value.length > 0);
</script>

<style scoped>
.orbit-elements-table {
  pointer-events: auto;
}

.orbit-elements-card {
  min-width: 380px;
  max-width: 560px;
  color: #e5e9ef;
}

.card-title {
  font-weight: 700;
  letter-spacing: 0.02em;
}

.placeholder {
  color: #9aa3b0;
  font-size: 0.9rem;
}

.row-block {
  margin-bottom: 14px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
  padding-bottom: 10px;
}

.row-block:last-of-type {
  border-bottom: none;
  margin-bottom: 0;
  padding-bottom: 0;
}

.jd-line {
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 0.85rem;
  color: #7fb7ff;
  margin-bottom: 4px;
}

.block-text {
  background: linear-gradient(145deg, rgba(24, 29, 38, 0.9), rgba(15, 19, 25, 0.95));
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 6px;
  padding: 8px 10px;
  margin: 0;
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 0.82rem;
  color: #f0f3f8;
  white-space: pre;
  overflow-x: auto;
}
</style>
