// Generated by Copilot
<template>
  <!-- Need something to mount -->
  <div v-if="false">
    <slot />
  </div>
</template>

<script setup lang="ts">
console.log('SheetTab.vue loaded');
// Generated by Copilot
import { inject, onMounted, useSlots, defineProps } from 'vue';
import { type VNode } from 'vue';

interface TabRegistration {
  title: string;
  titleSlot?: () => VNode[] | undefined;
  contentSlot: { render: () => VNode[] | undefined };
}

const props = defineProps({
  title: {
    type: String,
    default: ''
  }
});

const registerTab = inject('registerTab') as ((tab: TabRegistration) => void);
// https://vuejs.org/api/composition-api-helpers#useslots
const slots = useSlots();

onMounted(() => {
  registerTab({
    title: slots['title'] ? '' : props.title,
    titleSlot: slots['title'],
    contentSlot: { render: () => slots.default?.() }
  });
});
</script>
