// Generated by Copilot
<template>
  <v-dialog
    id="text-info-sheet"
    v-model="show"
    :style="{
      '--info-sheet-width': props.infoSheetWidth,
      '--info-sheet-height': props.infoSheetHeight,
      '--info-text-height': props.infoTextHeight,
    }"
    :class="['info-sheet', `info-sheet-${props.infoSheetLocation}`]"
    :scrim="false"
    persistent
    no-click-animation
    absolute
    location="bottom"
    :transition="props.infoSheetTransition"
  >
    <v-card height="100%">
      <v-tabs
        id="tabs"
        v-model="tab"
        height="32px"
        :color="props.accentColor"
        :slider-color="props.accentColor"
        dense
      >
        <v-tab
          v-for="(tabObj, i) in tabs"
          :key="i"
          class="info-tabs"
          tabindex="0"
          @click="setActiveTab(i)"
          @keyup.enter="setActiveTab(i)"
        >
          <component :is="tabObj.titleSlot || 'h3'">
            {{ tabObj.title }}
          </component>
        </v-tab>
      </v-tabs>
        
      <font-awesome-icon
        id="close-text-icon"
        class="control-icon"
        icon="times"
        size="lg"
        tabindex="0"
        @click="show = false"
        @keyup.enter="show = false"
      ></font-awesome-icon>

      <v-window
        id="tab-items"
        v-model="tab"
        class="pb-2 no-bottom-border-radius"
      >
        <v-window-item
          v-for="(tabObj, i) in tabs"
          :key="tabObj.title + i"
          class="scrollable"
        >
          <v-card class="no-bottom-border-radius scrollable">
            <v-card-text>
              <component :is="tabObj.contentSlot" />
            </v-card-text>
          </v-card>
        </v-window-item>
      </v-window>
      <slot />
    </v-card>
  </v-dialog>
</template>


<script setup lang="ts">
import { ref, provide, defineProps, defineModel, defineEmits, type Ref } from 'vue';
import { type VNode } from 'vue';
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
console.log('TabSheetDrawer.vue setup loaded');

interface TabRegistration {
  title: string;
  titleSlot?: () => VNode[] | undefined;
  contentSlot: { render: () => VNode[] | undefined };
}

const props = defineProps({
  accentColor: {
    type: String,
    default: "#235985"
  },
  cssVars: {
    type: Object,
    default: () => ({})
  },
  infoSheetLocation: {
    type: String,
    default: "bottom"
  },
  infoSheetTransition: {
    type: String,
    default: "dialog-bottom-transition"
  },
  infoSheetWidth: {
    type: String,
    default: "30vh"
  },
  infoSheetHeight: {
    type: String,
    default: "30vh"
  },
  infoTextHeight: {
    type: String,
    default: "calc(30vh - 25px)"
  }
});

const show = defineModel('show', {
  type: Boolean,
  default: false
});
const tab = defineModel('tab', {
  type: Number,
  default: 0
});
const emit = defineEmits(['update:show', 'update:tab', 'tab-change']);
const tabs: Ref<TabRegistration[]> = ref([]);


function registerTab(tab: TabRegistration) {
  console.log(`Registering tab: ${tab.title}`);
  if (tabs.value.some(t => t.title === tab.title)) {
    console.warn(`Tab with title "${tab.title}" is already registered.`);
    return;
  }
  tabs.value.push(tab);
}

function setActiveTab(i: number) {
  if (tab.value !== i) {
    tab.value = i;
    emit('tab-change', i);
  }
}

provide('registerTab', registerTab);

</script>

<style lang="less">
.info-sheet {
  .v-overlay__content {
    align-self: flex-end;
    padding: 0;
    margin: 0 !important;
    max-width: 100% !important;
    height: var(--info-sheet-height) !important;
    width: var(--info-sheet-width) !important;
  }

  &.info-sheet-right .v-overlay__content {
    position: absolute;
    top: 0;
    right: 0;
    max-height: 100%;

    & .v-card, & .v-card .v-window {
      height: 100%;
    }
    & .info-tabs h3 {
      font-size: 10pt;
    }
  }

  #tabs {
    width: calc(100% - 3em);
    align-self: left;
  }

  .info-text {
    height: var(--info-text-height);
    padding-bottom: 25px;
    & a {
      text-decoration: none;
    }
  }
  .close-icon {
    position: absolute;
    top: 10px;
    right: 10px;
    z-index: 15;
    &:hover {
      cursor: pointer;
    }
    &:focus {
      color: white;
      border: 2px solid white;
    }
  }
  .scrollable {
    overflow-y: auto;
  }
  #tab-items {
    .v-card-text {
      font-size: ~"max(14px, calc(0.7em + 0.3vw))";
      padding-top: ~"max(2vw, 16px)";
      padding-left: ~"max(4vw, 16px)";
      padding-right: ~"max(4vw, 16px)";
      .end-spacer {
        height: 25px;
      }
    }
  }
  #close-text-icon {
    position: absolute;
    top: 0.25em;
    right: calc((3em - 0.6875em) / 3);
    color: white;
  }
  .v-tabs:not(.v-tabs--vertical).v-tabs--right>.v-slide-group--is-overflowing.v-tabs-bar--is-mobile:not(.v-slide-group--has-affixes) .v-slide-group__next, .v-tabs:not(.v-tabs--vertical):not(.v-tabs--right)>.v-slide-group--is-overflowing.v-tabs-bar--is-mobile:not(.v-tabs--has-affixes) .v-slide-group__prev {
    display: none;
  }
}
</style>
