// Generated by Copilot
import { ReferenceFrame, OrbitLayer, Color } from "@wwtelescope/engine";
// import { Color, Colors } from "@wwtelescope/engine";
import { LayerManager, LayerMap } from "@wwtelescope/engine";
import { asteroidDefinitions, asteroidDefinition2Frame, renderFrameAsChild } from "./asteroid_elements";

export const frankReferenceFrame = asteroidDefinitions[7085];

/**
 * Creates an OrbitLayer from a ReferenceFrame and adds it to the LayerManager
 * @param frame The ReferenceFrame to create the OrbitLayer from
 * @param layerName Optional name for the OrbitLayer [defaults to frame name]
 * @returns The created OrbitLayer
 */
export function orbitLayerFromFrame(frame: ReferenceFrame, layerName?: string): OrbitLayer {
  const orbitLayer = new OrbitLayer();
  orbitLayer.set_frames([frame]);
  
  console.log(`Created orbit layer for frame ${frame.name} with id ${orbitLayer.id}`);
  console.log(orbitLayer);
  orbitLayer.set_name(layerName ?? frame.name);
  LayerManager.get_layerList()[orbitLayer.id as string] = orbitLayer;
  // LayerManager.set_version(LayerManager.get_version()+1);
  // LayerManager.loadTree();
  return orbitLayer;
}
  

/**
 * Manually create an orbit layer for asteroid 7085 Frank Sienkiewicz
 */
export function addObject(name: string | number, color = '#00ff00ff'): OrbitLayer | undefined {

  const elements = asteroidDefinitions[name];
  console.log('Adding object for', name, elements);
  if (!elements) {
    console.error(`Elements for Frank Sienkiewicz (7085) not found. Available IDs: ${Object.keys(asteroidDefinitions).join(", ")}`);
    return;
  }
  const frame = asteroidDefinition2Frame(elements);
  console.log('Created frame for:',name, frame);

  // If you want to render this orbit using WWT's *child frame* orbit-path rendering (instead of OrbitLayer),
  // use `addObjectAsChild()` below. OrbitLayer.draw resets renderContext.world which can create apparent
  // rotations when comparing to other layers.
  const orbitLayer = orbitLayerFromFrame(frame, `Orbit of ${frame.name}`);
  console.log('Created orbit layer:', name, orbitLayer);
  orbitLayer.set_enabled(true);
  console.log(orbitLayer);
  // add it to the "Sun" and "Sky" maps
  if (LayerManager.get_allMaps()['Sun']) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    LayerManager.get_allMaps()['Sun']!.layers.push(orbitLayer);
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    LayerManager.get_allMaps()['Sun']!.open = true;
  } else {
    console.error("LayerManager.get_allMaps()['Sun'] is undefined");
  }

  // if (LayerManager.get_allMaps()['Sky']) {
  //   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  //   LayerManager.get_allMaps()['Sky']!.layers.push(orbitLayer);
  //   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  //   LayerManager.get_allMaps()['Sky']!.open = true;
  // } else {
  //   console.error("LayerManager.get_allMaps()['Sky'] is undefined");
  // }
  
  orbitLayer.set_color(Color.fromHex(color)); 

  // LayerManager._version++;
  LayerManager.set_version(LayerManager.get_version()+1);
  LayerManager.loadTree();
  console.log("Added Frank Sienkiewicz orbit layer");
  return orbitLayer;
}

export function addObjectAsChild(name: string | number, parent = "Sun", color = '#00ff00ff'): LayerMap | undefined {
  const elements = asteroidDefinitions[name];
  if (!elements) {
    console.error(`Elements for '${name}' not found. Available IDs: ${Object.keys(asteroidDefinitions).join(", ")}`);
    return;
  }

  const frame = asteroidDefinition2Frame(elements);
  const layerMap = renderFrameAsChild(frame, parent);
  console.log(`Registered '${frame.name}' as child of '${parent}'`);
  frame.set_representativeColor(Color.fromHex(color));
  frame.showAsPoint = false;
  return layerMap;
}


export async function addAsteroidLayer() {
  const asteroidName = "franksienkiewicz";

  // Manually calculated TLE
  const tle = `ASTEROID 07085
1  7085U 00000    25324.50000000 4.6387e+11 00000-0 8.68965e-07  0    00
2  7085   2.7461 121.2364 2533387 197.0036 120.1682 8.68965e-07    00
`;
  
  const asteroidLayer = LayerManager._loadOrbitsFile(asteroidName, tle, 'Sun');
  asteroidLayer.set_color(Color.fromHex("#ff00d4ff"));
  LayerManager.loadTree();
  // console.log('Adding asteroid layer for', asteroidName);
  
  // fetch asteroid from MPC - takes a while
  const sunTarget = {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    get_name: () => "Sun"
  };

  LayerManager._getMpcAsTLE(asteroidName, sunTarget);
  
}