// Generated by Copilot
import { SpreadSheetLayer, LayerManager, Color, Coordinates, ELL } from "@wwtelescope/engine";
import { frankReferenceFrame } from "./createAsteroid";
import { addToWWTRenderLoop } from "./wwt-hacks";
import { engineStore } from "@wwtelescope/engine-pinia";

let frankSpreadsheetLayer: SpreadSheetLayer | null = null;

/**
 * Creates a spreadsheet layer that displays Frank's position as a point
 * The position is updated every frame based on the current Julian Date
 */
export function createFrankSpreadsheetLayer(): SpreadSheetLayer {
  if (frankSpreadsheetLayer) {
    return frankSpreadsheetLayer;
  }

  // Create the spreadsheet layer
  const layer = new SpreadSheetLayer();
  layer.set_name("Frank Position");
  layer.set_enabled(true);
  layer.set_color(Color.fromHex("#04ff00ff")); // Match the orbit color
  
  // Set coordinate type to spherical/RA-Dec (0 = spherical)
  layer.set_coordinatesType(0);
  layer.set_astronomical(true);
  layer.set_scaleFactor(50);
  layer.set_markerScale(0);

  // Add initial data point (will be updated in render loop)
  updateFrankPosition(layer);

  // Add to layer manager
  LayerManager.get_layerList()[layer.id as string] = layer;
  
  // Add to Sun map
  if (LayerManager.get_allMaps()['Sun']) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    LayerManager.get_allMaps()['Sun']!.layers.push(layer);
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    LayerManager.get_allMaps()['Sun']!.open = true;
  }

  // Increment version and reload tree
  LayerManager.set_version(LayerManager.get_version() + 1);
  LayerManager.loadTree();

  frankSpreadsheetLayer = layer;

  // Add to render loop to update position
  setupRenderLoopUpdates(layer);

  console.log("Created Frank spreadsheet layer");
  return layer;
}

/**
 * Updates Frank's position in the spreadsheet layer based on current time
 */
function updateFrankPosition(layer: SpreadSheetLayer): void {
  const store = engineStore();
  const currentTime = store.currentTime;
  
  // Convert to Julian Date
  const jd = currentTime.getTime() / 86400000 + 2440587.5;
  
  if (!frankReferenceFrame) {
    console.error("Frank reference frame not found");
    return;
  }
  // Get orbital elements from the reference frame
  const elements = {
    a: frankReferenceFrame.eoe.semiMajorAxis,
    e: frankReferenceFrame.eoe.eccentricity,
    i: frankReferenceFrame.eoe.inclination,
    w: frankReferenceFrame.eoe.argumentOfPerihelion,
    omega: frankReferenceFrame.eoe.longitudeOfAscendingNode,
    n: frankReferenceFrame.eoe.meanMotion,
    t: frankReferenceFrame.eoe.epoch,
    jdEquinox: frankReferenceFrame.eoe.epoch,
  };

  // Calculate rectangular coordinates (heliocentric)
  const position = ELL.calculateRectangularJD(jd, elements);
  
  // Convert to RA/Dec using Coordinates helper
  // The position from ELL is in AU, heliocentric
  const coords = Coordinates.cartesianToSpherical2(position.x, position.y, position.z);
  console.log(`Frank position at JD ${jd}: RA=${coords[0]} deg, Dec=${coords[1]} deg, Distance=${coords[2]} AU`);
  // coords returns [ra, dec, distance]
  // ra is in degrees, we need to convert to hours for display
  const raHours = coords[0] / 15; // degrees to hours
  const decDeg = coords[1];
  
  // Create CSV data for the spreadsheet layer
  // Format: RA (hours), Dec (degrees), size, color
  const csvData = `RA,DEC,Size,Color\r\n${raHours},${decDeg},10,#04ffff\r\n`;
  
  // Update the layer with new data
  layer.updateData(csvData, true, true, true);
}

/**
 * Sets up the render loop to continuously update Frank's position
 */
function setupRenderLoopUpdates(layer: SpreadSheetLayer): void {
  addToWWTRenderLoop(() => {
    updateFrankPosition(layer);
  });
}

/**
 * Removes the Frank spreadsheet layer
 */
export function removeFrankSpreadsheetLayer(): void {
  if (frankSpreadsheetLayer) {
    LayerManager.deleteLayerByID(frankSpreadsheetLayer.id as string, true, true);
    frankSpreadsheetLayer = null;
  }
}
